### ISSUE TITLE
How can i install it?

### ISSUE THREAD

**Issue by vacabernardo** [mautic/mautic-chat#2]
I put on plugins folder but doesn't work

**Comment by andrearuffini** [comment]
I have this problem too.

**Comment by Luisfmarkes** [comment]
This is the error i get when i try to clear cache

PHP Fatal error:  Class 'MauticAddon\MauticChatBundle\PluginBundleBase' not found in /home/bo001/public_html/emkt/plugins/MauticChatBundle/MauticChatBundle.php on line 19

**Comment by abhi038** [comment]
Same Problem

**Comment by Poltavtcev** [comment]
too...

**Comment by BillPackard** [comment]
I don't try install this. It is not works, thanks.
